# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/epi/PlanetSasha/gui/sasha_ui.ui'
#
# Created: Mon Nov 11 13:11:50 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Sasha(object):
    def setupUi(self, Sasha):
        Sasha.setObjectName(_fromUtf8("Sasha"))
        Sasha.resize(128, 80)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/epi.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Sasha.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Sasha)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        Sasha.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(Sasha)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Sasha.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(Sasha)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        Sasha.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionGPS = QtGui.QAction(Sasha)
        self.actionGPS.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/satellite.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGPS.setIcon(icon1)
        self.actionGPS.setObjectName(_fromUtf8("actionGPS"))
        self.actionGrass = QtGui.QAction(Sasha)
        self.actionGrass.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/grass_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGrass.setIcon(icon2)
        self.actionGrass.setObjectName(_fromUtf8("actionGrass"))
        self.actionJoystick = QtGui.QAction(Sasha)
        self.actionJoystick.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/joystick.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionJoystick.setIcon(icon3)
        self.actionJoystick.setObjectName(_fromUtf8("actionJoystick"))
        self.actionLonLat = QtGui.QAction(Sasha)
        self.actionLonLat.setCheckable(True)
        self.actionLonLat.setChecked(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/600px-Brosen_windrose.svg.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLonLat.setIcon(icon4)
        self.actionLonLat.setObjectName(_fromUtf8("actionLonLat"))
        self.actionExit = QtGui.QAction(Sasha)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/quit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon5)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionDB_setting = QtGui.QAction(Sasha)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/db.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDB_setting.setIcon(icon6)
        self.actionDB_setting.setObjectName(_fromUtf8("actionDB_setting"))
        self.actionNMEA = QtGui.QAction(Sasha)
        self.actionNMEA.setObjectName(_fromUtf8("actionNMEA"))
        self.actionData_2 = QtGui.QAction(Sasha)
        self.actionData_2.setCheckable(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/module-db.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionData_2.setIcon(icon7)
        self.actionData_2.setObjectName(_fromUtf8("actionData_2"))
        self.actionSavekml = QtGui.QAction(Sasha)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/saveinfo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSavekml.setIcon(icon8)
        self.actionSavekml.setObjectName(_fromUtf8("actionSavekml"))
        self.actionEpsg = QtGui.QAction(Sasha)
        self.actionEpsg.setObjectName(_fromUtf8("actionEpsg"))
        self.actionHidesliders = QtGui.QAction(Sasha)
        self.actionHidesliders.setCheckable(True)
        self.actionHidesliders.setObjectName(_fromUtf8("actionHidesliders"))
        self.actionHideSpinbox = QtGui.QAction(Sasha)
        self.actionHideSpinbox.setCheckable(True)
        self.actionHideSpinbox.setObjectName(_fromUtf8("actionHideSpinbox"))
        self.actionHide_place_position = QtGui.QAction(Sasha)
        self.actionHide_place_position.setCheckable(True)
        self.actionHide_place_position.setObjectName(_fromUtf8("actionHide_place_position"))
        self.actionHideStepTool = QtGui.QAction(Sasha)
        self.actionHideStepTool.setCheckable(True)
        self.actionHideStepTool.setObjectName(_fromUtf8("actionHideStepTool"))
        self.actionHideSlider = QtGui.QAction(Sasha)
        self.actionHideSlider.setCheckable(True)
        self.actionHideSlider.setObjectName(_fromUtf8("actionHideSlider"))
        self.actionJoystick_2 = QtGui.QAction(Sasha)
        self.actionJoystick_2.setIcon(icon3)
        self.actionJoystick_2.setObjectName(_fromUtf8("actionJoystick_2"))
        self.actionDataexp = QtGui.QAction(Sasha)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/ingranaggi.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDataexp.setIcon(icon9)
        self.actionDataexp.setObjectName(_fromUtf8("actionDataexp"))
        self.actionVrt = QtGui.QAction(Sasha)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/ingranaggio_icona.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVrt.setIcon(icon10)
        self.actionVrt.setObjectName(_fromUtf8("actionVrt"))
        self.actionGVrt = QtGui.QAction(Sasha)
        self.actionGVrt.setIcon(icon10)
        self.actionGVrt.setObjectName(_fromUtf8("actionGVrt"))
        self.actionGrassshell = QtGui.QAction(Sasha)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/512 Terminal.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGrassshell.setIcon(icon11)
        self.actionGrassshell.setObjectName(_fromUtf8("actionGrassshell"))
        self.actionModel = QtGui.QAction(Sasha)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/cubo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionModel.setIcon(icon12)
        self.actionModel.setObjectName(_fromUtf8("actionModel"))
        self.actionPref = QtGui.QAction(Sasha)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/tools.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPref.setIcon(icon13)
        self.actionPref.setShortcut(_fromUtf8(""))
        self.actionPref.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.actionPref.setObjectName(_fromUtf8("actionPref"))
        self.actionVectorOp = QtGui.QAction(Sasha)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/SquadraCompasso.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVectorOp.setIcon(icon14)
        self.actionVectorOp.setObjectName(_fromUtf8("actionVectorOp"))
        self.actionHW = QtGui.QAction(Sasha)
        self.actionHW.setCheckable(True)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/keyser-tux-wifi-logo-2300.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHW.setIcon(icon15)
        self.actionHW.setObjectName(_fromUtf8("actionHW"))
        self.actionBroadcast = QtGui.QAction(Sasha)
        self.actionBroadcast.setCheckable(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Ubuntu_connessione_Internet_.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBroadcast.setIcon(icon16)
        self.actionBroadcast.setObjectName(_fromUtf8("actionBroadcast"))
        self.actionCompass = QtGui.QAction(Sasha)
        self.actionCompass.setObjectName(_fromUtf8("actionCompass"))
        self.actionPan_Tool = QtGui.QAction(Sasha)
        self.actionPan_Tool.setObjectName(_fromUtf8("actionPan_Tool"))
        self.actionGt = QtGui.QAction(Sasha)
        self.actionGt.setCheckable(True)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/gui-help.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGt.setIcon(icon17)
        self.actionGt.setObjectName(_fromUtf8("actionGt"))
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionVectorOp)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(Sasha)
        QtCore.QMetaObject.connectSlotsByName(Sasha)

    def retranslateUi(self, Sasha):
        Sasha.setWindowTitle(_translate("Sasha", "Sasha", None))
        self.toolBar.setWindowTitle(_translate("Sasha", "toolBar", None))
        self.actionGPS.setText(_translate("Sasha", "GPS", None))
        self.actionGrass.setText(_translate("Sasha", "Grass", None))
        self.actionGrass.setToolTip(_translate("Sasha", "Grass", None))
        self.actionJoystick.setText(_translate("Sasha", "Joystick", None))
        self.actionJoystick.setToolTip(_translate("Sasha", "Joystick", None))
        self.actionLonLat.setText(_translate("Sasha", "LonLat", None))
        self.actionLonLat.setToolTip(_translate("Sasha", "LonLat", None))
        self.actionExit.setText(_translate("Sasha", "Preference", None))
        self.actionDB_setting.setText(_translate("Sasha", "DB-setting", None))
        self.actionNMEA.setText(_translate("Sasha", "NMEA", None))
        self.actionData_2.setText(_translate("Sasha", "Data", None))
        self.actionData_2.setToolTip(_translate("Sasha", "Data processing", None))
        self.actionSavekml.setText(_translate("Sasha", "savekml", None))
        self.actionEpsg.setText(_translate("Sasha", "Epsg", None))
        self.actionHidesliders.setText(_translate("Sasha", "hideslider", None))
        self.actionHideSpinbox.setText(_translate("Sasha", "Spinbox", None))
        self.actionHide_place_position.setText(_translate("Sasha", "Place-Position", None))
        self.actionHideStepTool.setText(_translate("Sasha", "StepTool", None))
        self.actionHideSlider.setText(_translate("Sasha", "tabPosition", None))
        self.actionJoystick_2.setText(_translate("Sasha", "Joystick", None))
        self.actionDataexp.setText(_translate("Sasha", "Export", None))
        self.actionVrt.setText(_translate("Sasha", "DataTools", None))
        self.actionGVrt.setText(_translate("Sasha", "vrt", None))
        self.actionGrassshell.setText(_translate("Sasha", "grassshell", None))
        self.actionModel.setText(_translate("Sasha", "model", None))
        self.actionPref.setText(_translate("Sasha", "Preference", None))
        self.actionPref.setToolTip(_translate("Sasha", "Preference", None))
        self.actionVectorOp.setText(_translate("Sasha", "VectorOp", None))
        self.actionHW.setText(_translate("Sasha", "HW", None))
        self.actionHW.setToolTip(_translate("Sasha", "Serial", None))
        self.actionBroadcast.setText(_translate("Sasha", "actionBroadcast", None))
        self.actionCompass.setText(_translate("Sasha", "Compass", None))
        self.actionPan_Tool.setText(_translate("Sasha", "Pan-Tool", None))
        self.actionGt.setText(_translate("Sasha", "Gt", None))

import resources_rc
